"""Initial migration.

Revision ID: 55cfdeb73bb9
Revises: 
Create Date: 2023-07-18 19:58:42.568380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cfdeb73bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Chiave primaria della tabella'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Nome identificativo dell'azione"),
    sa.Column('description', sa.Text(), nullable=True, comment="Descrizione estesa dell'azione"),
    sa.PrimaryKeyConstraint('id'),
    schema='cmi_charts',
    comment="Tabella d'appoggio con tutte le azioni possibile dell'utente"
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Chiave primaria della tabella'),
    sa.Column('mail', sa.String(length=255), nullable=False, comment="Mail dell'utente usata come identificativo unico in fase di autenticazione"),
    sa.Column('password', sa.String(length=255), nullable=False, comment="Parola d'ordine del'utente criptata con BCrypt"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    schema='cmi_charts',
    comment="Tabella anagrafica per gli utenti dell'applicazione"
    )
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Chiave primaria della tabella'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Chiave esterna vero la tabella users'),
    sa.Column('action_id', sa.Integer(), nullable=False, comment='Chiave esterna vero la tabella actions'),
    sa.Column('remote_addr', sa.String(length=255), nullable=True, comment="Ip dell'utente"),
    sa.Column('http_user_agent', sa.String(length=255), nullable=True, comment="Programma di navigazione dell'utente"),
    sa.Column('datetime', sa.String(length=25), nullable=False, comment='Data ed orario'),
    sa.ForeignKeyConstraint(['action_id'], ['cmi_charts.actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cmi_charts.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cmi_charts',
    comment='Tabella delle azioni effettuate degli utenti'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_actions', schema='cmi_charts')
    op.drop_table('users', schema='cmi_charts')
    op.drop_table('actions', schema='cmi_charts')
    # ### end Alembic commands ###
